### ISSUE TITLE
Pulling decennial data with get_census?

### ISSUE THREAD

**Issue by dannyedgel** [walkerke/pygris#12]
I use the get_census function from pygris.data to pull ACS data with no issue, but I can't use almost the exact same settings to pull decennial data. I can't parse the error, either. Here's a watered-down version of my call:
`get_census(
        dataset = 'dec/dp',
        year = 2020,
        variables = 'DP1_0001C',
        params = {
            'for': 'county:*',
            'in': 'state:53',
            'key': API_KEY
        },
        return_geoid = True,
        guess_dtypes = True
   )`

And I get this error: 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/e/edgel/.local/lib/python3.11/site-packages/pygris/data.py", line 85, in get_census
>     df = pd.DataFrame(req.json()[1:], columns=req.json()[0])
>                       ^^^^^^^^^^
>   File "/software/anaconda/lib/python3.11/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by walkerke** [comment]
Hmm - I just ran your code without issue.  Are you still having this problem?

**Comment by dannyedgel** [comment]
Sorry, I realized after this that I was loading the wrong API key. I was still having issues pulling block-level data, but I realized that the decennial census API doesn't currently support it for 2020.

**Comment by dannyedgel** [comment]
Thank you! Maybe I'll re-adjust to using DHC variables
